version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./api/src:/app/api
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - './ui:/app/ui'
      - '/app/ui/node_modules'
    ports:
      - 3001:3000
    depends_on:
      - api
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: >
      npm run start
